"""mcp_tokens_session_idx

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 23:37:17.744723

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_mcp_tokens_session_id", "mcp_tokens", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mcp_tokens_session_id", table_name="mcp_tokens")
    # ### end Alembic commands ###
